# Generated by Django 6.0.4 on 2026-04-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('icon_class', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(choices=[('Principal', 'Principal'), ('Computer Science', 'Computer Science'), ('Commerce', 'Commerce'), ('Languages', 'Languages')], default='Computer Science', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='faculty/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['department', 'order', 'name'],
            },
        ),
    ]
