# Generated by Django 6.0.4 on 2026-04-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_announcement_course_facultymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], default='image', max_length=10)),
                ('file', models.FileField(upload_to='gallery/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Media',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sarvodaya Institute of Graduate Studies', max_length=200)),
                ('subtitle', models.CharField(default='Empowering Minds. Transforming Futures.', max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='media_type',
            field=models.CharField(choices=[('none', 'None'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='multimedia_file',
            field=models.FileField(blank=True, null=True, upload_to='announcements/'),
        ),
    ]
