# Generated by Django 6.0.4 on 2026-05-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gallerymedia_herosection_announcement_media_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerymedia',
            options={'ordering': ['category', 'order'], 'verbose_name_plural': 'Gallery Media'},
        ),
        migrations.AddField(
            model_name='gallerymedia',
            name='category',
            field=models.CharField(choices=[('Campus', 'Campus General'), ('BCA', 'BCA Gallery'), ('BCA AI', 'BCA AI & ML Gallery'), ('B.Com', 'B.Com Gallery')], default='Campus', max_length=20),
        ),
    ]
